image: golang

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd src 
    - go get -d .
    - go build

test:  
  stage: test
  script:
    - cd src 
    - go get -d .
    - go test
