version: '3.7'

services:
  website:
    build: .
    ports:
      - "5000:80"
    env_file: .env
    restart: always
    links:
      - postgres
  
  # Use postgres/example user/password credentials
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /var/data/hummingbird/postgres:/var/lib/postgresql/data
